image: alpine

stages: [trigger]

build:
  stage: trigger
  variables:
    JDK_VERSION: "22"
    DEBUG_LEVEL: "fastdebug"
    HASH: "${CI_COMMIT_SHORT_SHA}"
  trigger:
    project: DataDog/openjdk-build
    strategy: depend
    branch: main
    forward:
      pipeline_variables: true

test:
  stage: trigger
  needs: [build]
  variables:
    JDK_VERSION: "22"
    DEBUG_LEVEL: "fastdebug"
    HASH: "${CI_COMMIT_SHORT_SHA}"
  trigger:
    project: DataDog/apm-reliability/async-profiler-build
    strategy: depend
    branch: main
    forward:
      pipeline_variables: true